banco: 0..2
lote: 3..6
registro: 7..7
tipo_operacao: 8..8
tipo_servico: 9..10
res_banco1: 11..12
layout_lote: 13..15
res_banco2: 16..16
tipo_empresa: 17..17
num_empresa: 18..32
res_banco3: 33..52
cod_transmissao: 53..67
res_banco4: 68..72
nome_empresa: 73..102
informacao1: 103..142
informacao2: 143..182
numero_remessa: 183..190
data_gravacao: 191..198
res_banco5: 199..239